// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqcbmcorqkkrdwozwpgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxY2JtY29ycWtrcmR3b3p3cGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODg3MTAsImV4cCI6MjA3MTM2NDcxMH0.STlzJkDFUIP8exhJyog4MhDaKeOihxIysVdAzKLrU_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});